### PR TITLE
Fix linux build failure

### PR DESCRIPTION
**Pull request by sotaroikeda**
The patch fixes the build failure on linux. But I did not confirmed if it worked since  GLSL 1.50 was not supported on my VMWare Ubuntu env.

Jeff advised me that latest Ubuntu supports more GLSL versions. Then I updated the Ubuntu from v14.04 to v16.04. But the  GLSL 1.50 was still not supported even on Ubuntu v16.04.
## The error messages were the following. It seems like a problem of my vm linux env. Then I just put the patch since it could fix the linux build problem.

OpenGL version new 3.0 Mesa 11.2.0
Shader resource path: /home/sotaro/tmp-jeff/gecko-dev/gfx/webrender/res
Failed to compile shader: "/home/sotaro/tmp-jeff/gecko-dev/gfx/webrender/res/box_shadow.vs.glsl"
0:1(10): error: GLSL 1.50 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, and 3.00 ES

thread '<unnamed>' panicked at '-- Shader compile failed - exiting --', src/device.rs:836
note: Run with `RUST_BACKTRACE=1` for a backtrace.
fatal runtime error: failed to initiate panic, error 5
Redirecting call to abort() to mozalloc_abort

### CODE REVIEW

**Comment by sotaroikeda** [comment]
Replace offscreen_gl_context with a local source to remove a dependency to EGL on linux. To remove the dependency, only one line of code of offscreen_gl_context/src/platform/mod.rs was changed from the original source.

**Comment by kvark** [comment]
@sotaroikeda 
I got Linux running after #1 and #3.
Is EGL dependency a problem?
I'm also confused by the size of this PR (3K lines added?).

As for the GL version, looks like WR currently requires 3.2, judging by https://github.com/servo/webrender/issues/441.

**Comment by sotaroikeda** [comment]
> Is EGL dependency a problem?

It is not actually a problem. Yesterday I asked to jeff about 2 choices between removing EGL dependency and addding link to EGL. Then he chose removing EGL dependency.

> I'm also confused by the size of this PR (3K lines added?).

Majority of code is just adding offscreen_gl_context to local side.

**Comment by sotaroikeda** [comment]
> Majority of code is just adding offscreen_gl_context to local side.

It was modified to remove dependency to EGL on linux. only one line of code change.

**Pull request closed without merging**
