### PR TITLE
Build webrender as part of libgkrust

### PR DESCRIPTION
**Pull request by staktrace**
This builds webrender as part of libgkrust, which is built using the normal gecko build system (`mach build`). Note that you need to have `ac_add_options --enable-rust` in your mozconfig for this to work.

In the future, any updates to dependencies will require running `mach vendor rust` and committing the updates.

This is related to issue #21 , although that issue seems to cover a superset of these changes.

### CODE REVIEW

**Comment by staktrace** [comment]
Update after talking to @jrmuizel: there's some large things in here that we should try to avoid checking in if possible. We should be able to drop the freetype dependency, which will allow us to drop servo-freetype-sys (12 MB). Also we discovered that the lazy_static crate contains (probably accidentally) a ~2MB liblib.so file. I filed https://github.com/rust-lang-nursery/lazy-static.rs/issues/54 for that.

**Comment by jrmuizel** [comment]
Another thing we talked about is perhaps trying to drop the build time dependencies of gleam and just checking in the generated rust files.

**Comment by staktrace** [comment]
Just to update on the freetype situation: I am under the impression that the `servo/freetype` library (aka `freetype` in Cargo.toml) is the equivalent of a freetype header, and the `servo/libfreetype2` library (aka `servo-freetype-sys` in Cargo.toml) is the actual freetype library. Right now, since webrender depends on `freetype`, and `freetype` depends on `servo-freetype-sys`, the `mach vendor rust` command pulls them both in. This is not great, since `servo-freetype-sys` is enormous and we shouldn't really need it in Gecko, since we already have a copy of freetype and/or can link against the system freetype.

So what I tried yesterday was to modify `freetype` so that the dependency on `servo-freetype-sys` was optional (see [this commit](https://github.com/staktrace/rust-freetype/commit/9921cbb01f22b6d1997791b7b7daf373ca06f5e1)), and for our in-tree webrender, make sure to depend on `freetype` without the default features (see [this commit](https://github.com/staktrace/gecko-dev/commit/3829694b3321140b42db357fefce07787891e6ba)). That way servo still pulls in `servo-freetype-sys` by default but we do not in gecko. That seems to compile and link on my Linux machine. I have not yet gotten any linux webrender build to successfully run, so it might have runtime issues. I also haven't gotten any Windows build to complete successfully yet so I couldn't test it there.

I don't know if this approach is correct and at the moment I'm not pursuing it further.

**Comment by staktrace** [comment]
FWIW I got Linux webrender working after upgrading Ubuntu. It works both with and without `servo-freetype-sys` (by opting out of that feature as described above). On Windows I got my build working with `servo-freetype-sys` but not without, because it looks like gecko windows build doesn't know how to build the in-tree freetype.

**Comment by staktrace** [comment]
I'm having trouble building this on windows, even with cmake on the $PATH the build for servo-freetype-sys isn't finding it for some reason. Without these patches I was using the rust shell to `cargo build` webrender and that was working ok. the MozBuild shell is different though.

**Comment by staktrace** [comment]
This should be good to merge now.

**Pull request merged**
